# SwiftLint Configuration for Airbnb

# Ignored folders
excluded:
  - Carthage
  - Pods
  - .build

# Rules to apply
only_rules:
  - fatal_error_message
  - implicitly_unwrapped_optional
  - legacy_cggeometry_functions
  - legacy_constant
  - legacy_constructor
  - legacy_nsgeometry_functions
  - unused_optional_binding
  - unowned_variable_capture
  - custom_rules
  - trailing_whitespace
  - trailing_newline
  - identifier_name
  - file_length
  - space_around_operators
  - redundant_self
  - let_var_whitespace
  - semicolons
  - sorted_imports
  - block_comments
  - doc_comments
  - space_inside_braces
  - space_inside_parens

# Custom
trailing_whitespace:
  severity: error

trailing_newline:
  severity: error

file_length:
  warning: 300
  error: 500

identifier_name:
  min_length: 3
  max_length: 40
  excluded:
    - id

indentation: 2

custom_rules:
  no_objcMembers:
    name: "@objcMembers"
    regex: "@objcMembers"
    message: "Explicitly use @objc on each member you want to expose to Objective-C"
    severity: error
  no_direct_standard_out_logs:
    name: "Writing log messages directly to standard out is disallowed"
    regex: "(\\bprint|\\bdebugPrint|\\bdump|Swift\\.print|Swift\\.debugPrint|Swift\\.dump)\\s*\\("
    match_kinds:
      - identifier
    message: "Don't commit `print(…)`, `debugPrint(…)`, or `dump(…)` as they write to standard out in release."
    severity: error
  no_file_literal:
    name: "#file is disallowed"
    regex: "(\\b#file\\b)"
    match_kinds:
      - identifier
    message: "Instead of #file, use #fileID"
    severity: error
  no_filepath_literal:
    name: "#filePath is disallowed"
    regex: "(\\b#filePath\\b)"
    match_kinds:
      - identifier
    message: "Instead of #filePath, use #fileID."
    severity: error
  no_unchecked_sendable:
    name: "`@unchecked Sendable` is discouraged."
    regex: "@unchecked Sendable"
    match_kinds:
      - attribute.builtin
      - typeidentifier
    message: "Avoid using `@unchecked Sendable`. Consider safe alternatives or explain why it's necessary."
    severity: error
